### ISSUE TITLE
Is MSTATUS.FS affecfed by modification of MISA.F

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-isa-manual#1149]
In an implementation where the F bit in MISA is writable, what should happen to the FS bits in MSTATUS when the F bit in MISA is changed from 1 to 0 by writing the MISA CSR?  Should the FS bits be set to "off" or left unchanged?

Similarly when F bit in MISA is changed from 0 to 1, should the FS bits be left unchanged or set to some specific value?

**Comment by aswaterman** [comment]
The answer is more complicated than you'd probably prefer.  First of all, note that the spec allows FS to be writable even if the F extension isn't implemented but S-mode _is_ implemented.  If the implementation chooses this option, then mstatus.FS must be unaffected by misa.F: i.e., it retains its value and it remains writable.

If the implementation chooses the other option--or if it's forced to choose the other option because it does not implement S-mode--then there are two relevant rules.  The first is that disabling an extension via misa is required to make the implementation behave as though the extension were not implemented.  This rule implies that, for this class of implementation, the FS field becomes read-only zero whenever misa.F=0.  The second rule is that state uniquely associated with the extension becomes undefined after re-enabling the extension.  This rule implies that the FS field assumes an unspecified value after misa.F transitions from 0 to 1.

If you're looking for a simple rule, and you're only concerned about systems that implement S-mode, here's the answer: make mstatus.FS completely unaffected by misa.F.
