### ISSUE TITLE
Exception type for implicit access in VS-stage address translation

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-isa-manual#1199]
Do we report a page-fault or a guest-page-fault for G-stage translations done for implicit memory access for VS-stage?

Spec says:

> For a memory access made to support VS-stage address translation (such as to read/write a VS-level page table), permissions are checked as though for a load or store, not for the original access type. However, any exception is always reported for the original access type (instruction, load, or store/AMO).

The original access would get a page-fault, is that what should be reported for the implicit access?

**Comment by ved-rivos** [comment]
Last bullet of the paragraph preceding the quoted paragraph specifies that a guest-page fault exception is raised instead of a regular page-fault exception. For memory accesses made to read or write a VS-stage PTE, the permissions are tested as though for a load or a store respectively, but if the permission is not provided then a guest-page fault of the original access type - an instruction, load, or store/AMO guest-page fault - is raised.

**Comment by jrahmeh** [comment]
Thank you.
