### ISSUE TITLE
Definition of HS-qualified instruction when TVM=1

### ISSUE THREAD

**Issue by sealman-Kuo** [riscv/riscv-isa-manual#1231]
Section 9.6.1 of the spec states:
![螢幕擷取畫面 2024-02-16 173644](https://github.com/riscv/riscv-isa-manual/assets/160225806/166e7b3f-7803-487f-8b35-2891a8cec9ad)

The term “HS-qualified” is used in the specification to decide whether to raise an “illegal instruction” or “virtual instruction” exception when V=1.

When TVM=0, an instruction is considered HS-qualified if it can be executed in HS-mode.

However, the specification does not clarify the conditions under which an instruction is HS-qualified when TVM=1.

For example, it is not specified whether accessing _**hgatp**_ in VS-mode would raise an “illegal instruction” or “virtual instruction” exception when TVM=1.

**Comment by pdonahue-ventana** [comment]
If an instruction is valid to execute under the following 3 conditions then it is HS-qualified:
- in HS-mode
- TSR=0
- TVM=0

You can execute an access to hgatp in HS-mode when TSR=TVM=0 so it is HS-qualified.  This makes sense because virtual instruction exceptions are supposed to catch things that the hypervisor should emulate for nested virtualization.  If a guest hypervisor in VS-mode tries to access hgatp then this needs to be emulated.
