### ISSUE TITLE
For implementation with TLB, if a virtual address hit both 2M-pte and 4K-pte, shoud page fault arise?

### ISSUE THREAD

**Issue by jinyinghan324** [riscv/riscv-isa-manual#1328]
For implementation with TLB, it is possible that a virtual address hit both 2M-pte and 4K-pte and the translation result may be different. Should page fault arise, or use 2M-pte, or use 4K-pte?

**Comment by gfavor** [comment]
The Priv spec has this non-normative note that answers your question:

_It is permitted for multiple address-translation cache entries to co-exist for the same address.
This represents the fact that in a conventional TLB hierarchy, it is possible for multiple entries
to match a single address if, for example, a page is upgraded to a superpage without first clearing
the original non-leaf PTE’s valid bit and executing an SFENCE.VMA with rs1=x0, or if multiple
TLBs exist in parallel at a given level of the hierarchy. In this case, just as if an SFENCE.VMA
is not executed between a write to the memory-management tables and subsequent implicit read
of the same address: **it is unpredictable whether the old non-leaf PTE or the new leaf PTE is
used, but the behavior is otherwise well defined**._
