### ISSUE TITLE
About local order of A bit update.

### ISSUE THREAD

**Issue by zhuotianshu** [riscv/riscv-isa-manual#1751]
In section 10.3.1:

> Updates of the A bit may be performed as a result of speculation, even if the associated memory access ultimately is not performed architecturally. However, updates to the D bit, resulting from an explicit store, must be exact (i.e., non-speculative), and observed in program order by the local hart.

It specifies that D bit must be observed in program order, which means that
1. NO previous loads of the local HART can see this update
2. ALL subsequent loads of the local HART must see this update.

And in respect to A bit update, it specifies that it may perform "speculatively", which allows the first rule mentioned above to be violated. So my question is, can the second rule mentioned above also be violated? That is, is it okay if subsequent loads cannot see the A bit update caused by a previous memory access of the same HART?

**Comment by gfavor** [comment]
How do speculative A bit updates (which are implicit memory accesses) represent a violation of the first rule about loads and stores (which are explicit memory accesses), especially since rule 1 is only about D bit updates?  Or are you just observing that A bit updates aren't subject to a similar rule as rule 1 for D bit updates?  (Which doesn't mean that rule 1 for D bit updates can be violated.)

As far as rule 2 for D bit updates, it must not be violated (otherwise it wouldn't actually be a rule or requirement).

**Comment by zhuotianshu** [comment]
> Or are you just observing that A bit updates aren't subject to a similar rule as rule 1 for D bit updates? (Which doesn't mean that rule 1 for D bit updates can be violated.)

Yes, that's what I meant. My expression was incorrect.

**Comment by gfavor** [comment]
Since A bit updates are speculative, they are unordered wrt other surrounding loads/stores.

**Comment by zhuotianshu** [comment]
OK, thank you very much!
