### ISSUE TITLE
ISA naming string ambiguity

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-isa-manual#305]
Because ISA names are case-insensitive, the versioning scheme creates an ambiguity with respect to the packed-SIMD extension.  Does the string `rv64ima2p2` mean I + M + Av2.2, or I + M + Av2 + Pv2?

**Comment by kito-cheng** [comment]
Just a reference for you:

In current implementation of gnu assembler(Upstreamed), `p` will interpret as version separator if its following a number, otherwise interpret as `P` extension.

In order to prevent ambiguity, arch string will always separate with underline between different extension in current implementation of ELF attribute (Review in progress).

so for binutils, `rv64ima2p2` mean  I + M + Av2.2, `rv64ima2_p2` meaning I + M + Av2 + Pv2.

**Comment by aswaterman** [comment]
Yeah, one easy solution is to require an underscore between a version number and the P extension.
