### ISSUE TITLE
Canonical order for X*/SX* extensions

### ISSUE THREAD

**Issue by asb** [riscv/riscv-isa-manual#319]
The resolution for #273 indicated that Z extensions in the ISA naming string should be ordered first by category and then alphabetically. There is no guidance currently on the ordering requirements for X*/SX* extensions in the naming string. Must they be alphabetically ordered?

**Comment by kasanovic** [comment]
Given that we can not standardize X/SX names themselves, I think
alphabetical is about the only thing we can recommend/require.

This does bring up the issue of X namespace collisions, but given that
upstream tools won't support X-related extensions, it becomes a
vendor-specific toolchain problem.

I would resist the urge to manage this namespace, and instead push any
standardization effort into the standard namespace.  There's no point
creating two different standard namespaces.  There are benefits to
having contained anarchy.

Krste


>>>>> On Fri, 21 Dec 2018 05:25:09 -0800, Alex Bradbury <notifications@github.com> said:

| The resolution for #273 indicated that Z extensions in the ISA naming string should be ordered first by category and then
| alphabetically. There is no guidance currently on the ordering requirements for X*/SX* extensions in the naming string.
| Must they be alphabetically ordered?

| —
| You are receiving this because you are subscribed to this thread.
| Reply to this email directly, view it on GitHub, or mute the thread.*
