### ISSUE TITLE
What category for NMI (exception or interrupt)?

### ISSUE THREAD

**Issue by Melflyu** [riscv/riscv-isa-manual#473]
NMI is a non-mask, asynchronous interrupt and it is used to handle the machine error. The event causes an immediate jump to an implementation-defined NMI vector running in M-mode regardless of the state of a hart’s interrupt enable bits.

The RISC-V Privileged Architectures specification only states the description below:
>the values written to mcause on an NMI are implementation-defined, but a value of 0 is reserved to mean “unknown cause" 

But the document did not clearly indicate it's an exception or interrupt.

This will cause some issues in designing the debug module. Here has some example
1. The single-step behavior may be a difference for NMI when it is an exception or interrupts. please the single-step description below
> If executing or fetching that instruction causes an exception, Debug Mode is re-entered immediately after the PC is changed to the exception handler and the appropriate tval and cause registers are updated.

Let me show an example for single-step scenario:
If NMI is an exception:
T0: Single-step resume
T1: NMI taken. Single-step trigger is fired.
T2: Enter debug mode
T3: Execute first instruction on the NMI trap handler

If NMI is an interrupt:
T0: Single-step resume
T1: NMI taken
T2: Execute first instruction on the NMI trap handler. Single-step trigger is fired.
T3: Enter debug mode

2. the trigger fire should be generated after NMI when the trigger is set to interrupt trigger.

**Comment by kasanovic** [comment]
NMIs are interrupts (it says so right in the name...)

But the text in the manual is confusing.  Because NMIs are sent to a different vector, the mcause codes could be organized differently than the regular interrupt mcause codes.  Where the spec says "a value of 0" is written to mcause, it should really state an "Exception Code of 0" , with mcause still having the high Interrupt bit set as for regular interrupts.  I'll make the change/clarification.
