### ISSUE TITLE
What is the motivating use case for writable misa?

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-isa-manual#52]
After the discussion on riscv/riscv-qemu#59 I realize I don't know myself.

**Comment by aswaterman** [comment]
Emulating less-capable systems.

Disabling C extension to help with code that requires proof that indirect jumps can't jump to the middle of an instruction.

**Comment by kasanovic** [comment]
>>>>> On Sat, 22 Apr 2017 18:20:16 -0700, Andrew Waterman <notifications@github.com> said:

| Emulating less-capable systems.

And emulating non-standard extensions that stomp on standard
extensions.

| Disabling C extension to help with code that requires proof that indirect jumps
| can't jump to the middle of an instruction.

| —
| You are receiving this because you are subscribed to this thread.
| Reply to this email directly, view it on GitHub, or mute the thread.*
