### ISSUE TITLE
Reserve mtvec[1:0], stvec[1:0] for future vectored interrupt/exception extension

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-isa-manual#6]
Not especially important for Unix-like systems, so probably only an optional M-mode feature.

Setting LSB of mtvec could enable vectored interrupt mode.  Could place interrupt vectors below mtvec, and the single trap vector at mtvec.  That is, if it's an interrupt, jump to {mtvec[(XLEN-1) : (log2(XLEN)+2)], (~cause << 2)}.

**Comment by David-Horner** [comment]
This extension is possible in v1.11 as the low order bit of mtvec is "enforced" zero currently.

Explicitly reserving the low order bit, (indeed 2 low order bits even) to be zero in the v1.10 is a clean up I'd like to see for all hart writable addresses in CSR registers.  
Reserving the two low order bits allow for future expansion with minimal adverse impact to current designs (it becomes a convention that is beneficial to ensure that C mode cannot be assumed.)

Reserving space allows for non-standard implementations of a vectoring mechanism.

If the attempt is to proved pre-emptive specification so that early implementers do not  dictate a suboptimal defacto standard, then reservation should help address that. As would explicit v1.10 sections that are stipulated as in flux and not meeting the v1.10  "that .. will set the bar for making
backwards-incompatible changes very high indeed" objective.

**Comment by aswaterman** [comment]
Agreed.
