### ISSUE TITLE
HFENCE.GVMA when changing HGATP and reclaiming VMID

### ISSUE THREAD

**Issue by ingallsj** [riscv/riscv-isa-manual#722]
The description for `satp` includes this text:

> If the new address space’s page tables have been modified, **or if an ASID is reused,** it may be necessary to execute an SFENCE.VMA instruction (see Section 4.2.1) after writing satp.

The description for `hgatp` includes this text:

> If the new virtual machine’s guest physical page tables have been modified, it may be necessary to execute an HFENCE.GVMA instruction (see Section 5.3.2) **before or** after writing hgatp.

Differences bolded between the two.  Can we please make these additions to the spec?
1. "If the new virtual machine’s guest physical page tables have been modified, **or if a VMID is reused,**"
2. "it may be necessary to execute an SFENCE.VMA instruction **before or** after writing satp."

**Comment by aswaterman** [comment]
Note that all of this text is effectively non-normative because of the intentionally vague verb "may".  So, while I haven't thought through the software implications of the proposed changes yet, they will also end up being effectively non-normative.

**Comment by aswaterman** [comment]
@gfavor and I were trying to decide whether the right fix was to make both say "before or after" or make both simply say "after".  For posterity, I'm jotting down my justification for writing "before or after" for both.

There is a case where the SFENCE.VMA must precede the `satp` write: when the mapping for the supervisor code page where the PC points has been modified.  This happens during the Linux boot process, for example: https://github.com/torvalds/linux/blob/a9b9669d98229c1f6d228697af99a9b01b7b69ac/arch/riscv/kernel/head.S#L121

And of course there's a case where the `satp` write must precede the SFENCE.VMA: on implementations without ASIDs, for example, the TLB must be flushed on a context switch after the new process' page table has been loaded.  https://github.com/torvalds/linux/blob/a9b9669d98229c1f6d228697af99a9b01b7b69ac/arch/riscv/mm/context.c#L201

So, "before or after" is accurate for satp.

For hgatp, "before or after" is also correct, but for different a reason.  Since `hgatp` and `vsatp` cannot be active when `hgatp` is being written, and TLB fills can't occur for inactive `atp` registers, it doesn't matter whether the HFENCE.GVMA precedes the `hgatp` write or vice-versa.

**Comment by ingallsj** [comment]
Thanks, the revised text completely closes this.

For posterity, further justification for writing "before or after" for both:

> Since `hgatp` and `vsatp` cannot be active when `hgatp` is being written

They may be activated from HS or HU mode by a HLS instruction, potentially speculatively.

**Comment by gfavor** [comment]
To be more precise (for the record), there is no HU mode or HLS instruction.  The correct statement would be:

They may be activated by an HLV/HLVX/HSV instruction, or even normal load/store instructions when executed with MPRV=1 and MPV/MPP indicating VS or VU mode.

A question for Andrew:  Do these targeted load/store actions (that do just one specific load/store operation "as if" in a different execution mode) open the door to unlimited walking of the page tables and caching of address translations during that "moment"?  Currently I believe the answer is yes.  But these are distinctive cases of doing a VS/VU-mode access - and temporarily activating VS/VU-mode translation - while executing outside of VS/VU modes and instead in M/HS/U mode.

I'm not suggesting need for a change; just raising the question to make sure we would all agree on that allowed arch behavior.

**Comment by aswaterman** [comment]
That wasn't what @daniellustig and I intended in writing "the address-translation algorithm may be executed speculatively for any guest virtual address when such an instruction is executed": we meant that, if HLV/HSV is _non-speculatively_ executed, then additional translations may also occur.  ("when such an instruction is executed" implicitly means "non-speculatively".)

If misspeculated HLV/HSV are allowed to perform table walks, then we've got to call a spade a spade: `hgatp` and `vsatp` would then be active 100% of the time the processor is in HS-mode.  But this would contradict the previous couple sentences, which indicate that `hgatp` and `vsatp` are only active in VS-/VU-mode and when executing HLV/HSV.

It's pretty clear to me the intent of the spec was to forbid speculative execution of HLV/HSV instigating table walks.  This is certainly deserving of a non-normative note.  Or, if we decide we don't like this definition and want to permit misspeculated HLV/HSV to perform table walks, then we need to make a normative change to the spec, and say that `hgatp` and `vsatp` are active in HS-mode, too.

(It's probably obvious, but for completeness I'll note that nothing forbids speculative execution of HLV/HSV when they hit in the TLB.  In that case, any side effect of speculation is a side effect that could have occurred for some other reason.)

**Comment by ingallsj** [comment]
> We'd also need to accept that HS-mode/M-mode speculation could fill VS-stage TLB entries, and could cause the A bit in VS-stage PTEs to become set (a side channel that's _architecturally_ visible to VS-mode!).)

I hadn't thought of this before.  My initial reaction is that this may also affect other established ISA(s).
