### ISSUE TITLE
bare-mode-only implementation constraints

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-isa-manual#785]
Section 4.3 of the Privileged Specification says:

_For implementations that make satp.MODE read-only zero (always Bare), attempts to execute an SFENCE.VMA instruction might raise an illegal instruction exception._

A first minor point: I think it would it clarify things to move this statement to section 4.2 (Supervisor Memory-Management Fence Instruction), since it is talking about that instruction.

Also, I've been digesting the Ssmpu specification proposal. This seems to raise the possibility of an implementation with Hypervisor mode and MPU only (no virtual memory). Is this a plausible implementation? If so, should a similar statement be added for `HFENCE.VVMA` and `HFENCE.GVMA`?

Finally, is it worth adding text to each of the Svnapot, Svinval and Svpbmt sections to say that they require at least one mode other than bare to be implemented as prerequisites?

Thanks.

**Comment by aswaterman** [comment]
I agree the sentence you quoted about SFENCE.VMA should be moved into the previous section; that looks like an editing error.

Currently, the H extension requires paging.  We can consider making the relaxation you suggested at a later date if those proposals are ultimately adopted and if the decision is contemporaneously made to relax the constraint.  (I have my doubts that we will do so, but it's not entirely my call.)

I'm not prepared to make the statement you suggested about Svinval, because it seems like the kind of thing we might need to back out of (consider e.g. that offering SFENCE.VMA is legal when satp.MODE is read-only zero--it seems strange to have a more stringent constraint on SINVAL.VMA).  However, stating that Svnapot and Svpbmt depend on Sv39 is reasonable to do.
