### ISSUE TITLE
[mh]envcfg.PBMTE when Svbpmt absent

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-isa-manual#791]
If `Svbpmt` is not implemented, are the new `[mh]envcfg.PBMTE` fields read-only zero? There is a comment of this form relating to the `FIOM` field, but nothing for `PBMTE`.

If there are eventually going to be a large number of enable fields in here, then it might be worth having a table that, for each field, summarizes when it is or may be read-only zero - otherwise this section is going to get very wordy, I think.

Thanks.

**Comment by aswaterman** [comment]
This is implicitly true already because of the clause "When PBMTE=1, Svpbmt is available for S-mode and G-stage address translation."  If PBMTE=1 but Svpbmt were unimplemented, the previous clause would be violated.

I don't have a problem making this more explicit for menvcfg.PBMTE, though.  (There's no reason to make it any more explicit for henvcfg.PBMTE, because that's already conditioned on menvcfg.PBMTE.)

I'm not going to make a table for now.
