### ISSUE TITLE
How to implementd int128 multiply ,div ,rem on a 64-bit machine????

### ISSUE THREAD

**Issue by yuyang-ok** [riscv/riscv-isa-manual#845]
I have no idea how to implement these functionality.
can Some Help or have a document about this.

**Comment by aswaterman** [comment]
The question isn't specific to RISC-V, so this isn't the appropriate forum in which to ask it.

But, since I happen to have an answer on hand, I'll point you to the following routines, which provide the upper 64 bits of a 128-bit product for unsigned, signed, and signed-by-unsigned, respectively.  (The lower 64 bits can be obtained just using the `*` operator.)

https://github.com/riscv-software-src/riscv-isa-sim/blob/e94d843e8b2772ec860258f006c8a3126a92a781/riscv/arith.h#L11-L44

But please ask follow-up questions in a computer arithmetic forum.
