### ISSUE TITLE
Undefined abbreviations

### ISSUE THREAD

**Issue by goekce** [riscv/riscv-isa-manual#887]
1. https://github.com/riscv/riscv-isa-manual/blob/1237e31fc205fdf5d66f1d874ac958a07aec44b7/src/rv32.tex#L600-L602

   I suppose `BTB` stands for *branch target buffer*. `BTB` may not be clear for an average reader. Probably it is better to write it out to assist the reading flow.

2. https://github.com/riscv/riscv-isa-manual/blob/1237e31fc205fdf5d66f1d874ac958a07aec44b7/src/rv32.tex#L45-L46
    
   `pc` was defined in chapter 2.1 as the register name for the program counter, but in chapter 2.4 the abbreviation `PC` pops up:

   https://github.com/riscv/riscv-isa-manual/blob/1237e31fc205fdf5d66f1d874ac958a07aec44b7/src/rv32.tex#L593-L596

   In my opinion `PC` could be replaced with `pc`, because *the* program counter in the register file is mentioned and not the general concept of program counters. I also noticed that `PC` is used several times in next chapters and also in preface. My hunch is that `pc` was introduced later.

   This should be obvious for the reader, but I do not know how stringent the editors are with commentaries.

What do the authors think?

**Comment by aswaterman** [comment]
I've fixed the first one.  Since we only use the term BTB in that one place, simply expanding the acronym in-line is the way to go.

I agree that replacing PC with `pc` is probably the way to go, but since it shows up so often and is thus a more disruptive change, I'll handle it as a PR so that others can weigh in.
